steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/clariversev1:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/clariversev1:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'clariversev1'
      - '--image'
      - 'gcr.io/$PROJECT_ID/clariversev1:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'MONGO_CONNECTION_STRING=${_MONGO_CONNECTION_STRING},MONGO_DATABASE_NAME=${_MONGO_DATABASE_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/clariversev1:$COMMIT_SHA'

substitutions:
  _MONGO_CONNECTION_STRING: 'mongodb://ranjith:Ranjith@34.68.23.71:27017/admin'
  _MONGO_DATABASE_NAME: 'sparzaai'
